# Generated by Django 5.2.5 on 2025-08-22 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Impresora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.PositiveIntegerField()),
                ('estudiante_nombre', models.CharField(max_length=120)),
                ('estudiante_cedula', models.CharField(blank=True, default='', max_length=30)),
                ('estado', models.CharField(choices=[('reservado', 'Reservado'), ('usado', 'Usado'), ('cancelado', 'Cancelado')], default='reservado', max_length=10)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('impresora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='impresoras.impresora')),
            ],
            options={
                'unique_together': {('impresora', 'fecha', 'hora')},
            },
        ),
    ]
