# Generated by Django 5.2.5 on 2025-08-22 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impresoras', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='estudiante_carrera',
            field=models.CharField(choices=[('Robotica e IA', 'Robotica e IA'), ('Sistemas Biomedicos', 'Sistemas Biomedicos'), ('Sistemas Computacionales', 'Sistemas Computacionales'), ('Software', 'Software'), ('Realidad Virtual Y videojuegos', 'Realidad Virtual Y videojuegos'), ('Transformacion Digital de Negocios', 'Transformacion Digital de Negocios')], default='Robotica e IA', max_length=100),
        ),
        migrations.AddField(
            model_name='reserva',
            name='estudiante_celular',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
