# Generated by Django 5.2.5 on 2025-08-22 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impresoras', '0002_reserva_estudiante_carrera_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='estudiante_carrera',
            field=models.CharField(choices=[('Robotica e IA', 'Robotica e IA'), ('Sistemas Biomedicos', 'Sistemas Biomedicos'), ('Sistemas Computacionales', 'Sistemas Computacionales'), ('Software', 'Software'), ('Realidad Virtual Y videojuegos', 'Realidad Virtual Y videojuegos'), ('Transformacion Digital de Negocios', 'Transformacion Digital de Negocios')], max_length=100),
        ),
    ]
