# Generated by Django 5.2.5 on 2025-08-24 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impresoras', '0005_reserva_tecnico_observaciones_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabReserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.PositiveIntegerField()),
                ('estudiante_nombre', models.CharField(max_length=120)),
                ('estudiante_cedula', models.CharField(blank=True, default='', max_length=30)),
                ('estudiante_celular', models.CharField(blank=True, default='', max_length=30)),
                ('estudiante_carrera', models.CharField(choices=[('Robotica e IA', 'Robotica e IA'), ('Sistemas Biomedicos', 'Sistemas Biomedicos'), ('Sistemas Computacionales', 'Sistemas Computacionales'), ('Software', 'Software'), ('Realidad Virtual Y videojuegos', 'Realidad Virtual Y videojuegos'), ('Transformacion Digital de Negocios', 'Transformacion Digital de Negocios')], default='Robotica e IA', max_length=100)),
                ('estado', models.CharField(choices=[('reservado', 'Reservado'), ('usado', 'Usado'), ('cancelado', 'Cancelado')], default='reservado', max_length=10)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('tecnico_observaciones', models.TextField(blank=True, default='')),
            ],
        ),
    ]
