# Generated by Django 5.2.3 on 2025-09-08 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impresoras', '0008_reserva_tecnico_observaciones_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buffers', to='impresoras.reserva'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='tipo',
            field=models.CharField(choices=[('NORMAL', 'Normal'), ('BUFFER', 'Buffer 1h')], default='NORMAL', max_length=10),
        ),
    ]
