# Generated by Django 5.2.3 on 2025-09-08 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impresoras', '0009_reserva_parent_reserva_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labreserva',
            name='estado',
            field=models.CharField(choices=[('reservado', 'Reservado'), ('usado', 'Usado'), ('penalizado', 'Penalizado'), ('cancelado', 'Cancelado')], default='reservado', max_length=12),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='estado',
            field=models.CharField(choices=[('reservado', 'Reservado'), ('usado', 'Usado'), ('penalizado', 'Penalizado'), ('cancelado', 'Cancelado')], default='reservado', max_length=12),
        ),
        migrations.AddIndex(
            model_name='labreserva',
            index=models.Index(fields=['fecha', 'hora'], name='impresoras__fecha_7929a4_idx'),
        ),
        migrations.AddIndex(
            model_name='reserva',
            index=models.Index(fields=['impresora', 'fecha', 'hora'], name='impresoras__impreso_4045ef_idx'),
        ),
        migrations.AddIndex(
            model_name='reserva',
            index=models.Index(fields=['fecha', 'hora'], name='impresoras__fecha_d0a9a9_idx'),
        ),
    ]
