# Generated by Django 5.2.3 on 2025-09-09 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_persona_no_show_count_persona_penalized_until'),
        ('impresoras', '0010_alter_labreserva_estado_alter_reserva_estado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Penalizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ambito', models.CharField(choices=[('impresoras', 'Impresoras'), ('laboratorio', 'Laboratorio')], max_length=20)),
                ('hasta', models.DateTimeField()),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penalizaciones', to='base.persona')),
            ],
        ),
    ]
