# Generated by Django 5.2.3 on 2025-09-18 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impresoras', '0011_penalizacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='labreserva',
            name='actividad',
            field=models.TextField(blank=True, default=''),
        ),
    ]
