# Generated by Django 5.2.3 on 2025-10-21 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impresoras', '0012_labreserva_actividad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maquina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('disponible', models.BooleanField(default=True)),
            ],
        ),
    ]
