# Generated by Django 5.2.3 on 2025-10-21 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('impresoras', '0013_maquina'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Maquina',
        ),
    ]
