# Generated by Django 5.2.3 on 2025-10-21 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impresoras', '0014_delete_maquina'),
    ]

    operations = [
        migrations.AddField(
            model_name='impresora',
            name='disponible',
            field=models.BooleanField(default=True),
        ),
    ]
