# Generated by Django 5.2.5 on 2025-08-19 19:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Componente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('ubicacion', models.CharField(blank=True, default='', max_length=200)),
                ('cantidad_total', models.PositiveIntegerField(default=0)),
                ('cantidad_disponible', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('cedula', models.CharField(max_length=20)),
                ('celular', models.CharField(blank=True, default='', max_length=20)),
                ('carrera', models.CharField(choices=[('Robótica e IA', 'Robótica e IA'), ('Sistemas Biomedicos', 'Sistemas Biomedicos'), ('Sistemas Computacionales', 'Sistemas Computacionales'), ('Realidad Virtual y Videojuegos', 'Realidad Virtual y Videojuegos'), ('Transformacion Digital de Negocios', 'Transformacion Digital de Negocios'), ('Software', 'Software')], max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('fecha_salida', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_entrada', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('prestado', 'Prestado'), ('devuelto', 'Devuelto')], default='prestado', max_length=12)),
                ('renovaciones', models.PositiveIntegerField(default=0)),
                ('vence_el', models.DateTimeField(blank=True, null=True)),
                ('componente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.componente')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.persona')),
            ],
            options={
                'ordering': ['-fecha_salida'],
            },
        ),
    ]
