# Generated by Django 5.2.5 on 2025-08-19 19:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='componente',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='componente',
            name='actualizado_en',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='componente',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='componente',
            name='nombre',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='carrera',
            field=models.CharField(choices=[('Robotica e IA', 'Robotica e IA'), ('Sistemas Biomedicos', 'Sistemas Biomedicos'), ('Sistemas Computacionales', 'Sistemas Computacionales'), ('Software', 'Software'), ('Realidad Virtual Y videojuegos', 'Realidad Virtual Y videojuegos'), ('Transformacion Digital de Negocios', 'Transformacion Digital de Negocios')], max_length=120),
        ),
    ]
