# Generated by Django 5.2.3 on 2025-09-08 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_componente_activo_componente_actualizado_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='no_show_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='persona',
            name='penalized_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
