# Generated by Django 5.2.3 on 2025-09-09 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_persona_no_show_count_persona_penalized_until'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='penalizado_impresoras_hasta',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='penalizado_lab_hasta',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
